org: maximdevoir
app: labels-manager
service:
  name: labels-manager

provider:
  name: aws
  runtime: nodejs10.x
  region: ${opt:region, 'us-west-2'} # Overwrite the default region used. Default is us-east-1 (N. Virginia)
  logRetentionInDays: 14 # Set the default RetentionInDays for a CloudWatch LogGroup
  environment:
    APP_ID: ${env:APP_ID}
    WEBHOOK_SECRET: ${env:WEBHOOK_SECRET}
    PRIVATE_KEY_PATH: ${env:PRIVATE_KEY_PATH}

functions:
  router:
    handler: dist/serverless_handler.main
    memorySize: 128 # Overwrite the default memory size. Default is 1024
    timeout: 10 # The default is 3 seconds. Note: API Gateway current maximum is 30 seconds
    environment:
      LOG_FORMAT: json
    events:
      - http:
        path: /
        method: post
